set(ITKGPUFiniteDifference_LOADED 1)
set(ITKGPUFiniteDifference_ENABLE_SHARED "1")
set(ITKGPUFiniteDifference_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PUBLIC_DEPENDS "ITKCommon;ITKGPUCommon")
set(ITKGPUFiniteDifference_TRANSITIVE_DEPENDS "ITKCommon;ITKFiniteDifference;ITKGPUCommon")
set(ITKGPUFiniteDifference_PRIVATE_DEPENDS "")
set(ITKGPUFiniteDifference_LIBRARIES "ITKCommon")
set(ITKGPUFiniteDifference_INCLUDE_DIRS "${ITK_INSTALL_PREFIX}/include/ITK-5.2")
set(ITKGPUFiniteDifference_LIBRARY_DIRS "")
set(ITKGPUFiniteDifference_RUNTIME_LIBRARY_DIRS "${ITK_INSTALL_PREFIX}/lib")
set(ITKGPUFiniteDifference_TARGETS_FILE "")
set(ITKGPUFiniteDifference_FACTORY_NAMES "")

